/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift.logschema;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-03-09")
public enum DeviceType implements org.apache.thrift.TEnum {
  WEBAPP(0),
  IOS(1),
  ANDROID(2),
  OTHER(3);

  private final int value;

  private DeviceType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static DeviceType findByValue(int value) { 
    switch (value) {
      case 0:
        return WEBAPP;
      case 1:
        return IOS;
      case 2:
        return ANDROID;
      case 3:
        return OTHER;
      default:
        return null;
    }
  }
}
